export type OtaReconciliationStatus = "PENDING" | "MATCHED" | "DISPUTED" | "NOT_APPLICABLE";
export interface OtaReconciliation { reservation_id: number; guest_name: string; room_id: string; booking_source: string; gross_revenue: number; commission: number; net_revenue: number; status: OtaReconciliationStatus | string; booked_at: string; }
export interface VatInvoice { id: number; invoice_id: number; vat_invoice_number: string; tax_rate: number; taxable_amount: number; tax_amount: number; total_amount: number; customer_type: string; customer_name: string; tax_code: string | null; company_name: string | null; company_address: string | null; status: string; xml_status: string; issued_at: string; created_by: string; }
export interface VatInvoiceRequest { invoice_id: number; customer_type: string; customer_name: string; tax_code?: string; company_name?: string; company_address?: string; taxable_amount?: number; }
export interface AttendanceRecord { id: number; employee_id: string; work_date: string; clock_in: string | null; clock_out: string | null; status: string; source: string; device_event_id: string | null; note: string | null; }
export interface AttendanceInput { employee_id: string; work_date: string; clock_in?: string | null; clock_out?: string | null; status: string; source?: string; device_event_id?: string; note?: string; }
export interface LeaveRequest { id: number; employee_id: string; leave_type: string; start_date: string; end_date: string; reason: string; shift_swap_with: string | null; status: string; requested_by: string; approver: string | null; decided_at: string | null; created_at: string; }
export interface LeaveRequestInput { employee_id: string; leave_type: string; start_date: string; end_date: string; reason: string; shift_swap_with?: string; }
export interface StockItem { id: string; name: string; category: string; unit: string; current_quantity: number; safety_threshold: number; service_id: string | null; active: boolean; }
export interface StockMovementInput { item_id: string; movement_type: "RECEIVE" | "ISSUE" | "RETURN" | "WASTE" | "ADJUST"; quantity: number; reason?: string; }
export interface TechnicalAsset { id: string; name: string; category: string; location_type: string; room_id: string | null; floor: number | null; location: string; brand_model: string | null; installed_on: string | null; next_maintenance: string | null; status: string; original_value: number; note: string | null; active: boolean; }
export interface TechnicalAssetInput { id: string; name: string; category: string; location_type: string; room_id?: string; floor?: number; location: string; brand_model?: string; installed_on?: string; next_maintenance?: string; status?: string; original_value?: number; note?: string; }
